// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXb2cmY3VLtfzh1LXgApoW4bFcVZ3y6V4',
    appId: '1:36233298887:web:2fd734114b9a89e3094fe2',
    messagingSenderId: '36233298887',
    projectId: 'fedyashashlik-4444e',
    authDomain: 'fedyashashlik-4444e.firebaseapp.com',
    storageBucket: 'fedyashashlik-4444e.appspot.com',
    measurementId: 'G-97JR6MJYP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4YHUjDS4HD7v9v-2-pf8F1DO6Oca-kxM',
    appId: '1:36233298887:android:f8bb10945196e40c094fe2',
    messagingSenderId: '36233298887',
    projectId: 'fedyashashlik-4444e',
    storageBucket: 'fedyashashlik-4444e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9IPwumbqcANJzfQ9WyHPCK1_LcdK3Ct0',
    appId: '1:36233298887:ios:dd3d1263fe5b0955094fe2',
    messagingSenderId: '36233298887',
    projectId: 'fedyashashlik-4444e',
    storageBucket: 'fedyashashlik-4444e.appspot.com',
    iosClientId: '36233298887-a2qr6adci237s8u8kvqjsco96knlrre8.apps.googleusercontent.com',
    iosBundleId: 'com.example.fedyaShashlik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9IPwumbqcANJzfQ9WyHPCK1_LcdK3Ct0',
    appId: '1:36233298887:ios:dd3d1263fe5b0955094fe2',
    messagingSenderId: '36233298887',
    projectId: 'fedyashashlik-4444e',
    storageBucket: 'fedyashashlik-4444e.appspot.com',
    iosClientId: '36233298887-a2qr6adci237s8u8kvqjsco96knlrre8.apps.googleusercontent.com',
    iosBundleId: 'com.example.fedyaShashlik',
  );
}
